
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * THIS INTERFACE IS DEPRECATED AS OF JULY 2015. Please use MESSAGE_INTERVAL instead. A data stream is not a fixed set of messages, but rather a
 * recommendation to the autopilot software. Individual autopilots may or may not obey
 * the recommended messages.
 */
public class MAV_DATA_STREAM {
    public static final int MAV_DATA_STREAM_ALL = 0; /* Enable all data streams | */
    //       MAVLINK_MSG_ID_RAW_IMU - time_usec:1099511606821 xacc:-112 yacc:-41 zacc:-1031 xgyro:0 ygyro:37 zgyro:2 xmag:149 ymag:-259 zmag:0
//       MAVLINK_MSG_ID_SCALED_IMU2 - time_boot_ms:16777129 xacc:-139 yacc:6 zacc:-984 xgyro:-2 ygyro:-128 zgyro:19 xmag:0 ymag:0 zmag:0
//       MAVLINK_MSG_ID_SCALED_PRESSURE
    public static final int MAV_DATA_STREAM_RAW_SENSORS = 1; /* Enable IMU_RAW, GPS_RAW, GPS_STATUS packets. | */
    //        MAVLINK_MSG_ID_POWER_STATUS - Vcc:5074 Vservo:0 flags:4
//        MAVLINK_MSG_ID_MEMINFO - brkval:0 freemem:4640
//        MAVLINK_MSG_ID_MISSION_CURRENT - seq:0
//        MAVLINK_MSG_ID_NAV_CONTROLLER_OUTPUT - nav_roll:0.0 nav_pitch:0.0 alt_error:0.0 aspd_error:0.0 xtrack_error:0.0 nav_bearing:0 target_bearing:0 wp_dist:0
//        MAVLINK_MSG_ID_SYS_STATUS - onboard_control_sensors_present:33553423 onboard_control_sensors_enabled:6298639 onboard_control_sensors_health:33553423 load:19 voltage_battery:5347 current_battery:367 drop_rate_comm:0 errors_comm:0 errors_count1:0 errors_count2:0 errors_count3:0 errors_count4:0 battery_remaining:98
    public static final int MAV_DATA_STREAM_EXTENDED_STATUS = 2; /* Enable GPS_STATUS, CONTROL_STATUS, AUX_STATUS | */
    //MAVLINK_MSG_ID_RC_CHANNELS - time_boot_ms:2949425 chan1_raw:0 chan2_raw:0 chan3_raw:0 chan4_raw:0 chan5_raw:0 chan6_raw:0 chan7_raw:0 chan8_raw:0 chan9_raw:0 chan10_raw:0 chan11_raw:0 chan12_raw:0 chan13_raw:0 chan14_raw:0 chan15_raw:0 chan16_raw:0 chan17_raw:0 chan18_raw:0 chancount:0 rssi:0
//        MAVLINK_MSG_ID_SERVO_OUTPUT_RAW - time_usec:1099511627734 servo1_raw:1100 servo2_raw:1100 servo3_raw:1100 servo4_raw:1100 servo5_raw:1100 servo6_raw:1100 servo7_raw:0 servo8_raw:0 port:0
    //MAVLINK_MSG_ID_RC_CHANNELS_RAW - time_boot_ms:3014615 chan1_raw:0 chan2_raw:0 chan3_raw:0 chan4_raw:0 chan5_raw:0 chan6_raw:0 chan7_raw:0 chan8_raw:0 port:0 rssi:0
    public static final int MAV_DATA_STREAM_RC_CHANNELS = 3; /* Enable RC_CHANNELS_SCALED, RC_CHANNELS_RAW, SERVO_OUTPUT_RAW | */
    public static final int MAV_DATA_STREAM_RAW_CONTROLLER = 4; /* Enable ATTITUDE_CONTROLLER_OUTPUT, POSITION_CONTROLLER_OUTPUT, NAV_CONTROLLER_OUTPUT. | */
    //        MAVLINK_MSG_ID_GLOBAL_POSITION_INT - time_boot_ms:2255384 lat:0 lon:0 alt:0 relative_alt:0 vx:0 vy:0 vz:0 hdg:0
    public static final int MAV_DATA_STREAM_POSITION = 6; /* Enable LOCAL_POSITION, GLOBAL_POSITION/GLOBAL_POSITION_INT messages. | */
    // MAVLINK_MSG_ID_ATTITUDE - time_boot_ms:16777175 roll:0.03758773 pitch:-0.11276547 yaw:0.0 rollspeed:-0.0016906792 pitchspeed:0.037194505 yawspeed:0.0033206763
    public static final int MAV_DATA_STREAM_EXTRA1 = 10; /* Dependent on the autopilot | */
    //        MAVLINK_MSG_ID_VFR_HUD - airspeed:0.0 groundspeed:0.0 alt:0.0 climb:0.0 heading:0 throttle:0
    public static final int MAV_DATA_STREAM_EXTRA2 = 11; /* Dependent on the autopilot | */
    //        MAVLINK_MSG_ID_HWSTATUS - Vcc:5078 I2Cerr:0
//        MAVLINK_MSG_ID_SYSTEM_TIME - time_unix_usec:0 time_boot_ms:2120790
//        MAVLINK_MSG_ID_VIBRATION - time_usec:2130706342 vibration_x:0.038504105 vibration_y:0.03512681 vibration_z:0.05987626 clipping_0:0 clipping_1:0 clipping_2:0
//        MAVLINK_MSG_ID_AHRS - omegaIx:0.0 omegaIy:0.0 omegaIz:0.0 accel_weight:0.0 renorm_val:0.0 error_rp:1.0 error_yaw:1.0
//        MAVLINK_MSG_ID_HWSTATUS - Vcc:5082 I2Cerr:0
    public static final int MAV_DATA_STREAM_EXTRA3 = 12; /* Dependent on the autopilot | */
    public static final int MAV_DATA_STREAM_ENUM_END = 13; /*  | */
}
            