/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE MISSION_ACK PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.enums.MAV_MISSION_RESULT;

/**
* Ack message during MISSION handling. The type field states if this message is a positive ack (type=0) or if an error happened (type=non-zero).
*/
public class msg_mission_ack extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_MISSION_ACK = 47;
    public static final int MAVLINK_MSG_LENGTH = 3;
    private static final long serialVersionUID = MAVLINK_MSG_ID_MISSION_ACK;


    
    /**
    * System ID
    */
    public short target_system;
    
    /**
    * Component ID
    */
    public short target_component;
    
    /**
    * See MAV_MISSION_RESULT enum
    */
    public short type;

    public String getTypeText() {
        return getTypeText(type);
    }
    public static String getTypeText(short result){
        String resultStr;
        switch (result) {
            case MAV_MISSION_RESULT.MAV_MISSION_ACCEPTED:
                resultStr = "设置成功";
                break;
            case MAV_MISSION_RESULT.MAV_MISSION_ERROR:
                resultStr = "任务指令被拒绝";
                break;
            case MAV_MISSION_RESULT.MAV_MISSION_UNSUPPORTED_FRAME:
                resultStr = "不支持该坐标系";
                break;
            case MAV_MISSION_RESULT.MAV_MISSION_UNSUPPORTED:
                resultStr = "不支持该命令";
                break;
            case MAV_MISSION_RESULT.MAV_MISSION_NO_SPACE:
                resultStr = "任务数过长";
                break;
            case MAV_MISSION_RESULT.MAV_MISSION_INVALID:
                resultStr = "参数设置错误";
                break;
            case MAV_MISSION_RESULT.MAV_MISSION_INVALID_PARAM1:
                resultStr = "PARAM1设置错误";
                break;
            case MAV_MISSION_RESULT.MAV_MISSION_INVALID_PARAM2:
                resultStr = "PARAM2设置错误";
                break;
            case MAV_MISSION_RESULT.MAV_MISSION_INVALID_PARAM3:
                resultStr = "PARAM3设置错误";
                break;
            case MAV_MISSION_RESULT.MAV_MISSION_INVALID_PARAM4:
                resultStr = "PARAM4设置错误";
                break;
            case MAV_MISSION_RESULT.MAV_MISSION_INVALID_PARAM5_X:
                resultStr = "PARAM5设置错误";
                break;
            case MAV_MISSION_RESULT.MAV_MISSION_INVALID_PARAM6_Y:
                resultStr = "PARAM6设置错误";
                break;
            case MAV_MISSION_RESULT.MAV_MISSION_INVALID_PARAM7:
                resultStr = "PARAM7设置错误";
                break;
            case MAV_MISSION_RESULT.MAV_MISSION_INVALID_SEQUENCE:
                resultStr = "任务序列号设置错误";
                break;
            case MAV_MISSION_RESULT.MAV_MISSION_DENIED:
                resultStr = "飞控不接受任何指令";
                break;
            default:
                resultStr = "未知返回码";
                break;
        }
        return resultStr;
    }

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_MISSION_ACK;
        
        packet.payload.putUnsignedByte(target_system);
        
        packet.payload.putUnsignedByte(target_component);
        
        packet.payload.putUnsignedByte(type);
        
        return packet;
    }

    /**
    * Decode a mission_ack message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.target_system = payload.getUnsignedByte();
        
        this.target_component = payload.getUnsignedByte();
        
        this.type = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_mission_ack(){
        msgid = MAVLINK_MSG_ID_MISSION_ACK;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_mission_ack(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_MISSION_ACK;
        unpack(mavLinkPacket.payload);
    }

          
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_MISSION_ACK -"+" target_system:"+target_system+" target_component:"+target_component+" type:"+type+"";
    }
}
        